[book]
authors = ["Ian Clarke"]
description = "User manual for the Kweb web framework"
language = "en"
multilingual = false
src = "src"
title = "The Kweb User Manual"

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[output.html]
git-repository-url = "https://github.com/kwebio/kweb-core"
edit-url-template = "https://github.com/kwebio/kweb-core/edit/master/docs/{path}"
site-url = "/book/"