# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: build

on:
  push:
    branches: [ master ]
    paths-ignore: [ 'docs/**', 'README.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ 'docs/**', 'README.md' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build and run tests
      run: ./gradlew build
    - name: Generate API documentation
      if: ${{github.event_name == 'push'}}
      run: ./gradlew dokkaHtml
    - name: Deploy API documentation to Github Pages
      if: ${{github.event_name == 'push'}}
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        branch: gh-pages
        single-commit: true
        folder: build/dokka/html
        target-folder: api
