name: Generate Kweb Book using mdbook

on:
  push:
    branches: [master]
    paths-ignore: [ 'README.md' ]
  schedule:
    # Once per day at midnight to ensure docs are using current Maven version as retrieved from Maven Central
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install mdbook
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo "rust-lang/mdBook" --bin mdbook --to ~/.cargo/bin
          curl --proto '=https' --tlsv1.2 -sSf https://rossmacarthur.github.io/install/crate.sh | bash -s -- --repo "badboy/mdbook-toc" --to ~/.cargo/bin
      - name: Substituting KWEB_VERSION
        run: |
          cd docs
          V=$(curl --silent "https://search.maven.org/solrsearch/select?q=g:io.kweb+AND+a:kweb-core&rows=20&wt=json" | jq -r '.response.docs[0].latestVersion')
          echo "Substituting version $V"
          sed -i "s/KWEB_VERSION/$V/g" src/gettingstarted.md
      - name: Build MDBook
        run: |
          mdbook --version
          mdbook-toc --version
          cd docs
          mdbook build
      - name: Validate hyperlinks
        uses: untitaker/hyperlink@0.1.26
        with:
          args: docs/book --sources src/
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs/book
          target-folder: book
